-- return {
--   require("plugins.colorschemes.gruvbox"),
--   require("plugins.colorschemes.rose-pine"),
--   require("plugins.colorschemes.catpuccin"),
--
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = "rose-pine",
--     },
--   },
-- }
