return {
  require("plugins.custom-plugins.oil"),
  -- require("plugins.custom-plugins.codieum"),
  require("plugins.custom-plugins.tmux-navigator"),
  require("plugins.custom-plugins.vim-test"),
  require("plugins.custom-plugins.cellular-animation"),
  require("plugins.custom-plugins.vim-fiugitive"),
  require("plugins.custom-plugins.fzf"),
  -- require("plugins.custom-plugins.winsurf-nvim"),
  -- require("plugins.custom-plugins.rest-nvim"),
  require("plugins.custom-plugins.kulala-nvim"),
  require("plugins.custom-plugins.tailwind-tools"),
  -- require("plugins.custom-plugins.gen-nvim"),
  -- require("plugins.custom-plugins.goyo"),
  -- require("plugins.custom-plugins.avante-ai"),
  -- require("plugins.custom-plugins.coding-companion"),
  -- require("plugins.custom-plugins.sg-cody"),
  -- require("plugins.custom-plugins.tree-sitter"),
}
